### ISSUE TITLE
Handle error accessing .env file

### ISSUE THREAD

**Issue by johnjohndoe** [jpadilla/django-project-template#3]
I stumbled into an error caused by a typo in [wsgi.py](https://github.com/jpadilla/django-project-template/blob/master/project_name/wsgi.py#L14) which prevented the settings from `.env` being imported. Since errors are not handled it took me days to find the actual problem. Therefore, I suggest you introduce some kind of error handling to notify the user.

I introduced an `AttributeError` as shown below. You might wanna replace it with a more general error class.

```python
try:
    dotenv.read_dotenv(
        os.path.join(os.path.dirname(os.path.dirname(__file__)), '.env'))
except AttributeError as e:
    print "Error reading .env: {0}".format(e)
    pass
```

**Comment by jpadilla** [comment]
Hmm, that's definitely not a typo. It's meant to catch any exception. When a file isn't found django-dotenv will issue a warning(not an exception) like "Not reading .env - it doesn't exist." The reason it's just a warning and not an exception is because the .env file is completely optional, mostly meant for development, while using real environment variables whenever you deploy to production, usually using the wsgi.py + something like gunicorn. I added the option to read the .env from the wsgi file as well for convenience while testing that out in development.

**Comment by johnjohndoe** [comment]
I had a typo here:

> os.path.join(os.path.dirname(os.path.direname(__file__)), '.env'))

This caused the failure to read the `.env` file.

Do I understand you right? You do not use `.env` in production?

**Comment by jpadilla** [comment]
Ah gotcha, yeah instead of swallowing any exception I should just be printing out whatever the message for the exception was, that would be good.

Yeah, I don't even commit my `.env` into my repository, it should be ignored. Though, I usually deploy on Heroku. But there's nothing stopping you of actually deploying your .env to your server and using that, don't see anything wrong with that.

**Comment by johnjohndoe** [comment]
Printing out whatever message comes would be helpful.

I normally commit an `example.env` which has all the property names. The `.env` prevented to be commited via `.gitignore`.

**Comment by jpadilla** [comment]
Done here 3b7a398f05de240e03b47e1b8c724f6d6700399f

**Comment by johnjohndoe** [comment]
Cool.
